/* Shared Tailwind CDN theme for TrailNotes prototype screens */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#00855d",
        "on-primary-fixed-variant": "#005137",
        "on-secondary-fixed-variant": "#344c39",
        "on-background": "#171c1f",
        "tertiary-container": "#66768d",
        "surface-variant": "#dfe3e7",
        "inverse-on-surface": "#edf1f5",
        tertiary: "#4d5d73",
        "surface-container-low": "#f0f4f8",
        "secondary-fixed-dim": "#b1ceb4",
        "secondary-container": "#cae7cc",
        secondary: "#4b644f",
        outline: "#6d7a72",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#f5fff7",
        "tertiary-fixed": "#d3e4fe",
        "inverse-primary": "#68dba9",
        "on-primary": "#ffffff",
        primary: "#006948",
        "on-tertiary-container": "#fdfcff",
        background: "#f6fafe",
        "surface-container-high": "#e4e9ed",
        surface: "#f6fafe",
        "on-tertiary-fixed-variant": "#38485d",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-highest": "#dfe3e7",
        "on-surface-variant": "#3d4a42",
        "surface-tint": "#006c4a",
        "outline-variant": "#bccac0",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#082010",
        "surface-container": "#eaeef2",
        "on-error": "#ffffff",
        "on-secondary-container": "#4f6953",
        "primary-fixed": "#85f8c4",
        "secondary-fixed": "#cdeacf",
        "on-primary-fixed": "#002114",
        "surface-bright": "#f6fafe",
        "primary-fixed-dim": "#68dba9",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-surface": "#171c1f",
        "surface-dim": "#d6dade",
        error: "#ba1a1a",
        "inverse-surface": "#2c3134",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
};
